function adicionarValor() {

    let nam = document.getElementById("username").value;
    let sur = document.getElementById("surname").value;
    let job = document.getElementById("job").value;
    let nome = nam + " " + sur;
    let espacoDiv = ' <div class="row justify-content-center" style="margin-top: 15rem;margin-bottom: 5rem;"> <div class="card" style="max-width: 50%"> <div id="dadosDeUsuario" class="card-header"> </div> <ul class="list-group list-group-flush" style="display: flex; flex-direction: column; justify-content: center; align-items: center;"> <p><h5>Código-fonte:</h5></p> <li class="list-group-item" style="max-width: 100%"> <textarea name="CaixaResultado" id="codigoFonte" cols="100" rows="10" style="font-family: monospace; font-size: smaller; max-width: 100%;"> </textarea> </li> <li class="list-group-item"> <a href="" onclick="copiar()" class="btn btn-primary"> Copiar o texto </a> </li> </ul> </div> </div>'
    //let espacoDiv = '<div class="row justify-content-center" style="margin-top: 15rem;margin-bottom: 5rem;"><div class="card"><div id="dadosDeUsuario" class="card-header"></div><ul class="list-group list-group-flush" style="text-align: center;"><h5>Código-fonte:</h5><li class="list-group-item" style="max-width: 40rem;"><code id="codigoFonte"></code></li></ul></div></div>'
    let result = ' <div data-zbluepencil-ignore="true" id="Zm-_Id_-Sgn" style="color: rgb(19, 19, 19); font-family: Verdana, sans-serif; line-height: 14px" > <div style="margin-bottom: 16px; text-align: left;"> <span style="font-size:12px"> Atenciosamente, </span> </div> <div id="Zm-_Id_-Sgn"> <table cellpadding="0" cellspacing="0"> <tbody style="font-family: Verdana, sans-serif"> <tr> <td colspan="2" style="width: 480px; padding-bottom: 5px; text-align: left;"> <span style="font-size: 14px; font-weight: bold"> Camilla Correia </span> </td> </tr> <tr> <td colspan="2" style="width: 480px; padding-bottom: 5px; height: 24px; text-align: left;"> <span style="font-size: 14px"> Diretora de Relações Externas </span> </td> </tr> <tr> <td style="width: 120px; vertical-align: middle" valign="middle"> <img alt="logo TITAN" src="https://bitbucket.org/TITANufba/marketing/raw/7c53f8689486cc3fab01aed74bae6b5e3c3ba146/logo/logo.png" width="122" height="122" style="margin-right: 18px" > </td> <td style="width: 450px; font-family: Arial, sans-serif; vertical-align: middle" valign="middle"> <div style="margin-bottom: 12px; text-align: left;"> <span style="font-size: 12px; font-style: italic;"> "Transformamos sonhos em soluções tangíveis" </span> </div> <div style="margin-bottom: 6px; text-align: left;"> <span style="font-size: 14px; font-weight: bold;" > Empresa Júnior de Engenharia da Computação da UFBA </span> </div> <div style="text-align: left;"> <span style="font-size: 12px;"> EPUFBA - 8º Andar. Sala 8.3.5 | R. Prof. Aristídes Novis, Nº 2, Federação. </span> </div> <div style="margin-bottom: 12px; text-align: left;"> <span style="font-size: 12px"> CEP: 40210-630, Salvador - BA. </span> </div> <table cellpadding="0" cellspacing="0"> <tbody> <tr> <td style="padding-top: 2px; padding-left: 1px"> <span style="display: inline-block; height: 27px"> <a href="https://www.instagram.com/titan_ufba" target="_blank" style="text-decoration: none" > <img alt="Instagram icon" src="https://bitbucket.org/TITANufba/marketing/raw/088c9625a9361dd5becd663cf9133e739b46caea/icones/instagram_icon.png" style="border: 0; height: 27px; width: 27px" > </a> <a href="https://pt.linkedin.com/company/ufbatitan" target="_blank" style="text-decoration: none" > <img alt="Linkedin icon" src="https://bitbucket.org/TITANufba/marketing/raw/a2d4b1caa670019e51f4718f1a2924ff94ae2a02/icones/linkedin_icon.png" style="border: 0px; height: 27px; width: 27px" > </a> </span> </td> </tr> </tbody> </table> </td> </tr> </tbody> </table> </div> </div>'; 
    let source = '<div data-zbluepencil-ignore="true" id="Zm-_Id_-Sgn" style="color: rgb(19, 19, 19); font-family: Verdana, sans-serif; line-height: 14px" > <div style="margin-bottom: 16px"> <span style="font-size:12px"> Atenciosamente, </span> </div> <div id="Zm-_Id_-Sgn"> <table cellpadding="0" cellspacing="0"> <tbody style="font-family: Verdana, sans-serif"> <tr> <td colspan="2" style="width: 480px; padding-bottom: 5px"> <span style="font-size: 14px; font-weight: bold">' + nome + '</span> </td> </tr> <tr> <td colspan="2" style="width: 480px; padding-bottom: 5px; height: 24px"> <span style="font-size: 14px">' + job + '</span> </td> </tr> <tr> <td style="width: 120px; vertical-align: middle" valign="middle"> <img alt="logo TITAN" src="https://bitbucket.org/TITANufba/marketing/raw/7c53f8689486cc3fab01aed74bae6b5e3c3ba146/logo/logo.png" width="122" height="122" style="margin-right: 18px" > </td> <td style="width: 395px; font-family: Arial, sans-serif; vertical-align: middle" valign="middle"> <div style="margin-bottom: 12px;"> <span style="font-size: 12px; font-style: italic"> "Transformamos sonhos em soluções tangíveis" </span> </div> <div style="margin-bottom: 6px;"> <span style="font-size: 14px; font-weight: bold;" > Empresa Júnior de Engenharia da Computação da UFBA </span> </div> <div> <span style="font-size: 12px"> EPUFBA - 8º Andar. Sala 8.3.5 | R. Prof. Aristídes Novis, Nº 2, Federação. </span> </div> <div style="margin-bottom: 12px"> <span style="font-size: 12px"> CEP: 40210-630, Salvador - BA. </span> </div> <table cellpadding="0" cellspacing="0"> <tbody> <tr> <td style="padding-top: 2px; padding-left: 1px"> <span style="display: inline-block; height: 27px"> <a href="https://www.instagram.com/titan_ufba" target="_blank" style="text-decoration: none" > <img alt="Instagram icon" src="https://bitbucket.org/TITANufba/marketing/raw/088c9625a9361dd5becd663cf9133e739b46caea/icones/instagram_icon.png" style="border: 0; height: 27px; width: 27px" > </a> <a href="https://pt.linkedin.com/company/ufbatitan" target="_blank" style="text-decoration: none" > <img alt="Linkedin icon" src="https://bitbucket.org/TITANufba/marketing/raw/a2d4b1caa670019e51f4718f1a2924ff94ae2a02/icones/linkedin_icon.png" style="border: 0px; height: 27px; width: 27px" > </a> </span> </td> </tr> </tbody> </table> </td> </tr> </tbody> </table> </div></div>';

    document.getElementById('resultado').innerHTML = espacoDiv;
    document.getElementById("dadosDeUsuario").innerHTML = result;
    document.getElementById('codigoFonte').innerText = source;
    alert('Obrigado por testar minha ferramenta! Sinta-se à vontade para sugerir melhoras ou modificar para si!')
    }


    function copiar() {
        /* Get the text field */
        var copyText = document.getElementById("codigoFonte");
      
        /* Select the text field */
        copyText.select();
        copyText.setSelectionRange(0, 99999); /*For mobile devices*/
      
        /* Copy the text inside the text field */
        document.execCommand("copy");
      
        /* Alert the copied text */
        alert("Texto copiado! ");
      } 

